### ISSUE TITLE
Do not patch liquid.theme

### ISSUE THREAD

**Issue by dolmen** [aborrero/pkg-liquidprompt#1]
Instead of patching `liquid.theme` in [debian/patches/debian-default-cfg.patch](https://github.com/aborrero/pkg-liquidprompt/blob/b919847525d1f9837adf8c3ac51540d279e0f4f0/debian/patches/debian-default-cfg.patch) I (the liquidprompt maintainer) would prefer that you add a `Debian.theme` with your own settings and keep `liquid.theme` the pristine one.

**Comment by aborrero** [comment]
Addressed here: https://github.com/aborrero/pkg-liquidprompt/commit/66ed8dcf90072317e6b35c6798d009426150079d

thanks
