### ISSUE TITLE
Don't use '.' to source scripts

### ISSUE THREAD

**Issue by dolmen** [aborrero/pkg-liquidprompt#2]
zsh does not support `.` as an alias to `source`.
In [debian/patches/debian-default-cfg.patch](https://github.com/aborrero/pkg-liquidprompt/blob/b919847525d1f9837adf8c3ac51540d279e0f4f0/debian/patches/debian-default-cfg.patch#L26), the `liquidpromptrc-dist` file is patched and a `.` command is added instead of `source`.

**Comment by aborrero** [comment]
Addressed here: https://github.com/aborrero/pkg-liquidprompt/commit/66ed8dcf90072317e6b35c6798d009426150079d

thanks
